# Generated by Django 5.1.7 on 2025-03-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='photo/default/default.jpg', upload_to='photo/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
